/**
 * Self-hosts the two typefaces: downloads the variable woff2 files from
 * Google Fonts (latin + latin-ext subsets) into public/fonts/ and writes
 * src/styles/fonts.css with matching @font-face rules. Run once; the files
 * are committed, so the site never calls a font CDN at runtime.
 *   node scripts/fetch-fonts.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const FONT_DIR = path.join(__dirname, '..', 'public', 'fonts');
const CSS_OUT = path.join(__dirname, '..', 'src', 'styles', 'fonts.css');
fs.mkdirSync(FONT_DIR, { recursive: true });

const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Newsreader:ital,opsz,wght@0,6..72,400..500;1,6..72,400..500&family=Archivo:wght@400..600&display=swap';

// A modern UA is required or Google serves TTF instead of woff2.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36';

const SUBSETS = new Set(['latin', 'latin-ext']);

const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text();

// Blocks look like: /* latin */ @font-face { ... url(...) ...; unicode-range: ...; }
const blockRe = /\/\*\s*([a-z-]+)\s*\*\/\s*@font-face\s*\{([\s\S]*?)\}/g;
const rules = [];
let match;

while ((match = blockRe.exec(css)) !== null) {
  const [, subset, body] = match;
  if (!SUBSETS.has(subset)) continue;

  const family = body.match(/font-family:\s*'([^']+)'/)[1];
  const style = body.match(/font-style:\s*(\w+)/)[1];
  const weight = body.match(/font-weight:\s*([\d\s]+)/)[1].trim();
  const stretch = body.match(/font-stretch:\s*([^;]+);/)?.[1]?.trim();
  const range = body.match(/unicode-range:\s*([^;]+);/)[1].trim();
  const url = body.match(/url\((https:[^)]+\.woff2)\)/)[1];

  const slug = `${family.toLowerCase()}-${subset}-${style}`;
  const file = `${slug}.woff2`;
  const buf = Buffer.from(await (await fetch(url)).arrayBuffer());
  fs.writeFileSync(path.join(FONT_DIR, file), buf);
  console.log(`${file} — ${(buf.length / 1024).toFixed(0)} KB`);

  rules.push(
    `/* ${family} — ${subset}, ${style} */\n@font-face {\n  font-family: '${family}';\n  font-style: ${style};\n  font-weight: ${weight};\n${
      stretch ? `  font-stretch: ${stretch};\n` : ''
    }  font-display: swap;\n  src: url('/fonts/${file}') format('woff2');\n  unicode-range: ${range};\n}`
  );
}

const header = `/* ---------------------------------------------------------------------------
   Self-hosted type — generated by scripts/fetch-fonts.mjs. Do not edit the
   rules by hand; re-run the script instead.
--------------------------------------------------------------------------- */\n\n`;
fs.writeFileSync(CSS_OUT, header + rules.join('\n\n') + '\n');
console.log(`fonts.css — ${rules.length} @font-face rules`);
